apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-fastapi
  labels:
    app: mlops-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-fastapi
  template:
    metadata:
      labels:
        app: mlops-fastapi
    spec:
      containers:
      - name: fastapi
        image: mlops-fastapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000